# Generated by Django 5.2.1 on 2025-06-13 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=70)),
                ('item_description', models.CharField(max_length=350)),
                ('item_category', models.CharField(choices=[('clothing', 'Clothing'), ('electronics', 'Electronics'), ('home_appliances', 'Home Appliances'), ('furniture', 'Furniture'), ('books', 'Books'), ('toys', 'Toys'), ('beauty', 'Beauty & Personal Care'), ('sports', 'Sports & Outdoors'), ('groceries', 'Groceries'), ('footwear', 'Footwear'), ('stationery', 'Stationery'), ('automotive', 'Automotive'), ('jewelry', 'Jewelry'), ('pet_supplies', 'Pet Supplies'), ('music', 'Musical Instruments'), ('gaming', 'Gaming'), ('mobile_accessories', 'Mobile Accessories'), ('luggage', 'Luggage & Travel'), ('health', 'Health & Wellness'), ('baby_products', 'Baby Products')], max_length=30)),
                ('item_quantity', models.IntegerField()),
                ('item_prices', models.IntegerField()),
            ],
        ),
    ]
