# Generated by Django 5.2.1 on 2025-06-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('clothing', 'clothing'), ('electronics', 'electronics'), ('home_appliances', 'home_appliances'), ('furniture', 'furniture'), ('books', 'books'), ('toys', 'toys'), ('beauty', 'beauty_personal_care'), ('sports', 'sports_outdoors'), ('groceries', 'groceries'), ('footwear', 'footwear'), ('stationery', 'stationery'), ('automotive', 'automotive'), ('jewelry', 'jewelry'), ('pet_supplies', 'pet Supplies'), ('music', 'musical_instruments'), ('gaming', 'gaming'), ('mobile_accessories', 'mobile_accessories'), ('luggage', 'luggage_travel'), ('health', 'health_wellness'), ('baby_products', 'baby_products')], max_length=30),
        ),
    ]
