# Generated by Django 5.2.1 on 2025-06-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_item_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_prices',
            new_name='item_price',
        ),
    ]
